### ISSUE TITLE
Win 64 1.5 Серый экран.

### ISSUE THREAD

**Issue by donexdoc** [AlexGyver/imageProcessor#2]
Проблема при запуске готового билда на версии 1.5 для Windows 10 x64. Просто серый экран и никаких возможных действий. На этом же ПК запускаектся билд версии 1.2 без проблем.

**Comment by AlexGyver** [comment]
Java jre обнови

**Comment by donexdoc** [comment]
не решило проблему

**Comment by AlexGyver** [comment]
Странно, я прямо сейчас работаю в проге на вин10х64 и всё ок. В версиях выше 1.2 вроде из такого серьезного добавилось только копирование в буфер, там отдельная java библиотека. Но никто не писал о проблемах

**Comment by donexdoc** [comment]
решил попробовать, когда консультировал человека в комментариях. У него тоже така проблема. https://vk.com/feed?w=wall-97877471_726454_r726529

**Comment by AlexGyver** [comment]
Попробуй запустить исходник, я не у компьютера

**Comment by donexdoc** [comment]
Я тоже уже не у компьютера, попробую сегодня вечером или завтра. отпишусь тут

**Comment by AlexGyver** [comment]
Оке тоже чекну вечером

**Comment by donexdoc** [comment]
В общем, я добрался до дома. Если запускать исходники в Processing, то все работает нормально, но если экспортировать приложение, то оно не запускается, ни 64 ни 32, ни с галочкой добаавления java ни без нее... Я не силен в Processing, но если смогу разобраться, то напишу.

**Comment by Astarxes** [comment]
Похожая проблема наблюдается в Linux Debian 10 x64. При запуске приложения на экране открывается пустое серое окно, и дальше ни чего не происходит. Если запустить приложение через терминал, там появляется следующее сообщение об ошибке:
```
The file "noImage.jpg" is missing or inaccessible, make sure the URL is valid or that the file has been added to your sketch and is readable.
java.lang.NullPointerException
	at imageProcessor.setup(imageProcessor.java:105)
	at processing.core.PApplet.handleDraw(PApplet.java:2432)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
```

**Comment by Astarxes** [comment]
Да, дело действительно оказалось в недостающих файлах. Я скачал релиз v1.2 и разместил полученные из него файлы noImage.jpg, langEN и langRU в корневой директории приложения новой версии. Теперь оно запускается без видимых проблем.

**Comment by donexdoc** [comment]
> Да, дело действительно оказалось в недостающих файлах. Я скачал релиз v1.2 и разместил полученные из него файлы noImage.jpg, langEN и langRU в корневой директории приложения новой версии. Теперь оно запускается без видимых проблем.

Отлично, спасибо за расследование, Думаю, на этом можно закрывать этот баг. Думаю, Александр поправит в следующем релизе. Странно, что запуская в процессинге исходники, такой проблемы не возникало.

**Comment by GyverLibs** [comment]
О, всего лишь файла не хватало? Сейчас поправлю
