### ISSUE TITLE
Oled 8 pix / byte bw

### ISSUE THREAD

**Issue by SinicinDenis** [AlexGyver/imageProcessor#4]
Здравствуйте, парсю вэб версию битмапера и к сожалению отсутствует ! Oled 8 pix / byte bw ! в настройках... существует либо 1pix byte что очень весомо по итогу, либо 8х горизонт \ 8х вертикаль что отображается не верно на олед.

как-то можно прикрутить Oled 8 pix / byte bw на веб версию? или как сделать чтоб отображалось коррэктно?

спасибо за работу, ваш вклад в развитие робототехники в России невозможно переоценить!

**Comment by GyverLibs** [comment]
привет, в каком формате олед хочет битмап? 8х горизонт \ 8х вертикаль это как раз стандартные

**Comment by SinicinDenis** [comment]
> привет, в каком формате олед хочет битмап? 8х горизонт \ 8х вертикаль это как раз стандартные

![photo_2024-08-14_16-37-09](https://github.com/user-attachments/assets/78bf878b-30c7-4a8a-83c0-86f07f5043e5)

этот битмап сделан в приложении imageProcessor 1.5 всё норм

![photo_2024-08-14_16-37-08](https://github.com/user-attachments/assets/a8e742e7-fac1-4ecd-baf7-4aa0b9919925)

а этот битмап сделан с помощью веб версии 8х горизонт.. и такая хрень

олед GyverOled

**Comment by GyverLibs** [comment]
оледу нужен вертикальный

**Comment by SinicinDenis** [comment]
8x vertical такая же картина
![photo_2024-08-14_17-23-37](https://github.com/user-attachments/assets/ac7f379a-859a-400b-8ecf-cc460e900312)

**Comment by GyverLibs** [comment]
это странно, 8x Vertical как раз тот формат который у gyveroled

**Comment by GyverLibs** [comment]
ага, всё таки не тот. Подумаю как лучше сделать тогда, сейчас как раз ковыряю битмапер и gyvergfx для нового оледа

**Comment by SinicinDenis** [comment]
gyvergfx вот это интересно, а где можно почитать про этот модуль?  oled и gfx совместимы же?

**Comment by GyverLibs** [comment]
несовместимы, в будущем олед будет работать на gyvergfx

**Comment by GyverLibs** [comment]
с конвертером кириллических шрифтов и огромной кучей возможностей

**Comment by SinicinDenis** [comment]
то есть есть смысл перейти на gfx ? и еще такой вопрос, существует возможность закидывать в imageProcessor папку с картинками ? для анимации, иначе руками по 150 картинок приходится лопатить

**Comment by GyverLibs** [comment]
в общем добавил новый режим, для оледа это 8x vertical row. работает

**Comment by SinicinDenis** [comment]
Ого!! )) это реально круто))

**Comment by GyverLibs** [comment]
> есть смысл перейти на gfx 

сейчас переходить некуда, это всё в разработке

> закидывать в imageProcessor папку

к сожалению нет, в будущем для  битмапера такой режим скорее всего будет

**Comment by SinicinDenis** [comment]
Спасибо большое

**Comment by AlexGyver** [comment]
добавил до кучи массовое преобразование и пример к оледу в ридми  есть

**Comment by SinicinDenis** [comment]
https://github.com/user-attachments/assets/ab6d5214-de1f-401c-9f25-cf88cb064de8

да, всё заработало

**Comment by SinicinDenis** [comment]
> добавил до кучи массовое преобразование и пример к оледу в ридми есть

Рэспэкт и уважуха))
Примеры в тему кстати, чет помню долго копал как массив такой создать
